#cloud-config

package_update: true
package_upgrade: true

groups:
  - docker

system_info:
  default_user:
    groups: [ docker ]

# load initial project packages
packages:
  - git
  - python3-pip
  - apt-transport-https
  - ca-certificates
  - curl
  - gnupg-agent
  - software-properties-common

#
runcmd:
  - curl -fsSL https://download.docker.com/linux/ubuntu/gpg | apt-key add -
  - add-apt-repository "deb [arch=$(dpkg --print-architecture)] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
  - apt-get update -y
  - apt-get install -y docker-ce docker-ce-cli containerd.io
  - systemctl start docker
  - systemctl enable docker

  - cd /home/ubuntu
  - git clone https://github.com/directdetour/MLOps-Project.git
  # Pull the latest mlflow image
  - docker pull ghcr.io/mlflow/mlflow

final_message: "The system is finally up, after $UPTIME seconds"